apiVersion: v2
name: zahori-process
description: Zahori Process Example Wikipedia
type: application
version: 1.0.1
appVersion: 0.1.13
maintainers:
  - name: Panel Sistemas Zahori Team
    email: info@zahori.io
