apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: {{ include "zahori-postgresql-chart.label" . }}
  name: {{ include "zahori-postgresql-chart.storage.claim" . }}
  namespace: {{ .Values.namespace }}
  annotations:
    {{- toYaml .Values.storage.annotations | nindent 4 }}   
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
{{- if and .Values.storage.provisioner (ne .Values.storage.provisioner "") }}
  storageClassName: {{ .Values.storage.provisioner }}
{{- end }}