apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: {{ include "zahori-postgresql-chart.label" . }}
  name: {{ include "zahori-postgresql-chart.statefulset.public" . }}
  namespace: {{ .Values.namespace }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ include "zahori-postgresql-chart.label" . }}
  serviceName: postgres
  template:
    metadata:
      annotations:
        {{- toYaml .Values.deployment.annotations | nindent 8 }} 
      labels:
        app: {{ include "zahori-postgresql-chart.label" . }}
    spec:
      containers:
      - env:
        - name: ZAHORI_DB_HOST
          value: {{ include "zahori-postgresql-chart.service.name" . }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: POSTGRES_PASSWORD
              name: {{ include "zahori-postgresql-chart.config.secret" . }}
        envFrom:
        - configMapRef:
            name: {{ include "zahori-postgresql-chart.config.public" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        name: postgres
        ports:
        - containerPort: 5432
          name: postgresdb
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: pv-data
      volumes:
      - name: pv-data
        persistentVolumeClaim:
          claimName: {{ include "zahori-postgresql-chart.storage.claim" . }}

