apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ include "zahori-scheduler.label" . }}
  name: {{ include "zahori-scheduler.service.name" . }}
  namespace: {{ .Values.namespace }}
  annotations:
      {{- toYaml .Values.service.annotations | nindent 4 }}  
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: portScheduler
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.port }}
  selector:
    app: {{ include "zahori-scheduler.label" . }}