apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ include "zahori-process.name" . }}
  name: {{ include "zahori-process.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: {{ .Values.service.port }}-{{ .Values.service.port }}
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.port }}
  selector:
    app: {{ include "zahori-process.name" . }}
