apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: {{ include "zahori-server-chart.label" . }}
  name: {{ include "zahori-server-chart.storage.claim" . }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  storageClassName: {{ include "zahori-server-chart.storageclass.name" . }}