{{- if .Values.traefik.enabled -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: openzahori-server-ingressroute
 {{- with .Values.traefik.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ .Values.namespace }}
spec:
  entryPoints:
  - web
  routes:
    {{- range .Values.traefik.hosts }}
  - kind: Rule
    match: Host({{ .host | quote }}) && PathPrefix({{ .prefix | quote }})
    services:
    - name: {{ include "zahori-server-chart.service.name" . }}
      port: {{ $.Values.service.port }}
    {{- end }}
{{- end }}




