apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zahori-postgresql-chart.config.secret" . }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.postgres.password }}
