apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ include "zahori-postgresql-chart.label" . }}
  name: {{ include "zahori-postgresql-chart.service.name" . }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: postgres
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.port }}
  selector:
    app: {{ include "zahori-postgresql-chart.label" . }}