# Default values for zahori-scheduler.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

resources:
  limits:
    cpu: 1000m
    memory: 500Mi
  requests:
    cpu: 300m
    memory: 256Mi

namespace: zahori

config:
  ZAHORI_CONSUL_HOST: "consul-ui"
  ZAHORI_CONSUL_PORT: "80"
  ZAHORI_SCHEDULER_PORT: "7070"

service:
  type: ClusterIP
  port: 7070

replicaCount: 1

image:
  repository: zahoriaut/zahori-scheduler
  pullPolicy: IfNotPresent
  tag: "1.0.0"
