apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: {{ include "zahori-server-chart.label" . }}
  name: {{ include "zahori-server-chart.storage.claim" . }}
  namespace: {{ .Values.namespace }}
  annotations:
    {{- toYaml .Values.storage.annotations | nindent 4 }}  
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  storageClassName: {{ .Values.storage.provisioner }}