apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ include "zahori-server-chart.label" . }}
  name: {{ include "zahori-server-chart.service.name" . }}
  namespace: {{ .Values.namespace }}
  annotations:
      {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: portServer
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.port }}
  selector:
    app: {{ include "zahori-server-chart.label" . }}