{{- if .Values.traefik.enabled -}}
apiVersion: {{ .Values.traefik.apiVersion }}
kind: IngressRoute
metadata:
  name: {{ include "zahori-server-chart.traefik.name" . }}
  namespace: {{ .Values.namespace }}
  annotations:
    {{- toYaml .Values.traefik.annotations | nindent 4 }}  
spec:
  entryPoints:
  - web
  routes:
  {{- range $host := .Values.traefik.hosts }}
      - match: Host(`{{ $host.host }}`) && PathPrefix(`{{ $host.prefix }}`)
        kind: Rule
        services:
          - name: {{ $host.service.name }}
            port: {{ $host.service.port }}
  {{- end }}
{{- end }}
