# Default values for zahori-moon.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: zahori

traefik:
  enabled: true
  apiVersion: "traefik.containo.us/v1alpha1"
  annotations:
  hosts:
    - host: "consul.test"
      prefix: "/"
      service:
        name: "consul-ui"
        port: 80

# valores para la dependencia "consul"
consul:
  ui:
    enabled: true
  global:
    name: consul
