name: Release Charts

on:
  push:
    branches:
      - master

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        
      - name: Import PGP Key
        run: |
          echo "${{ secrets.PGP_PRIVATE_KEY }}" | gpg --batch --yes --passphrase=${{ secrets.PGP_PASSPHRASE }} --import
          
      - name: Get PGP Key ID
        id: get-key-id
        run: |
          echo "::set-output name=key_id::$(gpg --list-secret-keys --keyid-format LONG | grep sec | awk '{print $2}' | awk -F'/' '{print $2}')"
                  
      - name: Add aerokube Helm repo
        run: |
          helm repo add aerokube https://charts.aerokube.com/

      - name: Add hashicorp Helm repo
        run: |
          helm repo add hashicorp https://helm.releases.hashicorp.com
          
      - name: Add zahori Helm repo
        run: |
          helm repo add zahori https://zahori-io.github.io/zahori-helm-charts          

      - name: Update Helm repos
        run: |
          helm repo update
        
      - name: Update dependencies
        run: |
          for dir in ./charts/*; do
            [ -d "$dir" ] && helm dependency update "$dir"
          done
          
      - name: Sign and Package Charts
        run: |
          mkdir signed-charts
          for dir in ./charts/*; do
            [ -d "$dir" ] && helm package "$dir" --sign --key "${{ steps.get-key-id.outputs.key_id }}" --keyring /home/runner/.gnupg/trustdb.gpg --destination ./signed-charts
          done    

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        with:
          charts_dir: ./signed-charts
        env:
          CR_TOKEN: "${{ secrets.TOKEN }}"
